apiVersion: apps/v1
kind: Deployment
metadata:
  name: flink-task-manager
  labels:
    app: flink-task-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flink-task-manager
  template:
    metadata:
      labels:
        app: flink-task-manager
    spec:
      containers:
      - name: flink-task-manager
        image: ttbb/flink:mate
        imagePullPolicy: Always
        resources:
          limits:
            memory: 4G
            cpu: 1000m
          requests:
            memory: 4G
            cpu: 1000m
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
                fieldPath: spec.nodeName
        - name: POD_NAME
          valueFrom:
            fieldRef:
                fieldPath: metadata.name
        - name: CLUSTER_ROLE
          value: "TASK_MANAGER"
