apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: flink-job-manager
  labels:
    app: flink-job-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flink-job-manager
  serviceName: "flink-job-manager"
  template:
    metadata:
      labels:
        app: flink-job-manager
    spec:
      containers:
      - name: flink-job-manager
        image: ttbb/flink:mate
        imagePullPolicy: Always
        resources:
          limits:
            memory: 4G
            cpu: 1000m
          requests:
            memory: 4G
            cpu: 1000m
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
                fieldPath: spec.nodeName
        - name: POD_NAME
          valueFrom:
            fieldRef:
                fieldPath: metadata.name
        - name: CLUSTER_ROLE
          value: "JOB_MANAGER"
        - name: JVM_ARGS
          value: "-Xms1024m -Xmx1024m -XX:MetaspaceSize=256M"
