apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rolebinding-coredns
  namespace: kube-system
subjects:
  - kind: ServiceAccount
    name: serviceaccount-coredns
    namespace: kube-system
roleRef:
  kind: Role
  name: role-coredns
  apiGroup: rbac.authorization.k8s.io
