apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: minio
  labels:
    app: minio
spec:
  replicas: 3
  selector:
    matchLabels:
      app: minio
  serviceName: "minio"
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
      - name: minio
        image: ttbb/minio:mate
        imagePullPolicy: Always
        resources:
          limits:
            memory: 512M
            cpu: 250m
          requests:
            memory: 512M
            cpu: 250m
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
                fieldPath: spec.nodeName
        - name: POD_NAME
          valueFrom:
            fieldRef:
                fieldPath: metadata.name
        - name: SERVICE_NAME
          value: "minio"
        - name: CLUSTER_ENABLE
          value: "true"
