apiVersion: v1
kind: Service
metadata:
  name: flink-job-manager
spec:
  selector:
    app: flink-job-manager
  clusterIP: None
  sessionAffinity: None
  ports:
    - protocol: TCP
      port: 8081
      name: flink-job-manager-ui
    - protocol: TCP
      port: 6123
      name: flink-job-manager-rpc
